### ISSUE TITLE
Failed to acquire DataKey after updating LuckPerms

### ISSUE THREAD

**Issue by SubtypeZero** [CodeCrafter47/BungeeTabListPlus#292]
I recently updated LuckPerms and it seems to have broken the tab list. Users are still being shown alphabetically but permission data is not being used and my log file is being flooded.
```
[19:28:31 WARN] [BungeeTabListPlus]: Failed to acquire data DataKey(id=luckperms:prefix, scope=Scope(id=bungee:player), type=de.codecrafter47.data.api.TypeToken@8054fe2, parameter=null) from SubtypeZero
java.lang.NoSuchMethodError: me.lucko.luckperms.api.User.getUserDataCache()Ljava/util/Optional;
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:43) ~[?:?]
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:29) ~[?:?]
at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
at de.codecrafter47.data.bungee.AbstractBungeeDataAccess.get(AbstractBungeeDataAccess.java:42) ~[?:?]
at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:71) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:540e160:157]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by SubtypeZero** [comment]
I would like to stress the fact that this is flooding my log file. I noticed this issue when it filled up the very small amount of space that I allow my proxy server to use (promptly causing the server to be stopped).

**Comment by CodeCrafter47** [comment]
Should be fixed in the latest dev-build: [https://ci.codecrafter47.de/job/BungeeTabListPlus/](https://ci.codecrafter47.de/job/BungeeTabListPlus/).

**Comment by SubtypeZero** [comment]
Alright, I just updated to the snapshot versions and I'm still seeing the same message
![log](https://user-images.githubusercontent.com/25497312/32983715-d5da5c84-cc5e-11e7-8b65-a37697f255da.png)

**Comment by SubtypeZero** [comment]
It turns out that it's not sorting by rank properly, but I would imagine that this would be fixed once the issue with LuckPerms has been resolved.
![tab](https://user-images.githubusercontent.com/25497312/32984202-8004a752-cc67-11e7-9f7e-0b4557173f37.png)

**Comment by CodeCrafter47** [comment]
Ok, but now the latest dev-build should really fix the issue: <https://ci.codecrafter47.de/job/BungeeTabListPlus/>.

Technically, I've also fixed weight and suffix providers, whereas previously I've only fixed the code that gets the prefix.

**Comment by SubtypeZero** [comment]
I just tested this on my server and it appears to be fixed, so I'm going to go ahead and close the issue. Thank you for sorting this out quickly.

**Comment by Seeroh** [comment]
Can't download the fix for this issue, as the Jenkins is not loading at all.

**Comment by CodeCrafter47** [comment]
Appears to be working just fine right now.

**Comment by Seeroh** [comment]
I'm either getting ERR_TIMED_OUT or ERR_CONNECTION_RESET issues in chrome. I was asleep when you responded, or I would have tested, then.

(I also just realized I posted in two separate issues, because I thought my this response didn't go through, and just redid the comment about the Jenkins. My mistake)

**Comment by CodeCrafter47** [comment]
https://ci.codecrafter47.de/ is up and running. I can connect to it just fine.

**Comment by Seeroh** [comment]
Then there appears to be some kind of issue that I cannot circumvent on my end. Trying on any of my browsers results in a timeout issue, and if I try using my phone, it directs me to a provider search page, saying the website is not available, or doesn't exist. I am currently using my phone for internet on my computer, so I do not know how to circumvent this, easily.

I could download the latest file to my server via wget, if I had a direct link, though.

Sorry for the trouble.
