### ISSUE TITLE
Bug with playerSets 

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [CodeCrafter47/BungeeTabListPlus#490]
When i create tablist with default dynamic_size file

```
showTo: "all"
priority: 0

# Hidden players show up on the tab list, avoids glitches
hiddenPlayers: VISIBLE

playerSets:
  all_players: all

# A simple header and footer
showHeaderFooter: true
header:
- '&cWelcome &f${viewer name}'
headerAnimationUpdateInterval: 1.0
footer:
- '&f&oPowered by BungeeTabListPlus'
footerAnimationUpdateInterval: 1.0

# We want a dynamic size tab list
type: DYNAMIC_SIZE

# Below are the options specific to the dynamic size tab list

# Here you can configure which players to display by specifying a player set.
# For this example we are using the `all_players` player set created above.
playerSet: all_players

# Here the order of the players can be configured.
playerOrder: "alphabetically"

# This option controls the format of the players names.
playerComponent: "${player name}"
```

and change
```
playerSets:
  all_players: all
```
to
```
playerSets:
  all_players: '${viewer server} == ${player server}'
```

it gaves me this error

```
[01:46:28 INFO]: CONSOLE executed command: /btlp reload
[01:46:28 ERROR] [BungeeTabListPlus]: Failed to deactivate tab overlay plugins/BungeeTabListPlus/tabLists/default.yml
java.lang.NullPointerException: null
        at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onDeactivate$2(ConfigTabOverlayProvider.java:70) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[01:46:28 INFO]: Successfully reloaded BungeeTabListPlus.
[01:46:28 ERROR] [BungeeTabListPlus]: Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/default.yml
java.lang.NullPointerException: null
        at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier$PlayerPlaceholderDataProvider.activate(DataHolderPlaceholderDataProviderSupplier.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier$PlayerPlaceholderDataProvider.activate(DataHolderPlaceholderDataProviderSupplier.java:53) ~[?:?]
        at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToStringExpression.onActivation(GenericPlaceholder.java:124) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToStringExpression.activate(GenericPlaceholder.java:104) ~[?:?]
        at de.codecrafter47.taboverlay.config.expression.AbstractBinaryToBooleanExpression.onActivation(AbstractBinaryToBooleanExpression.java:13) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.expression.AbstractBinaryToBooleanExpression.activate(AbstractBinaryToBooleanExpression.java:5) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet$PlayerEntry.<init>(AbstractPlayerSet.java:135) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet$PlayerEntry.<init>(AbstractPlayerSet.java:125) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet.activate(AbstractPlayerSet.java:40) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet.addListener(AbstractPlayerSet.java:67) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.activate(OrderedPlayerSetImpl.java:96) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.addListener(OrderedPlayerSetImpl.java:179) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.PlayersComponentView.onActivation(PlayersComponentView.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.DynamicSizeContentView.onActivation(DynamicSizeContentView.java:35) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24) ~[?:?]
        at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

My BTLP status:
```[01:52:31 INFO]: CONSOLE executed command: /btlp status
[01:52:31 INFO]: You are running BungeeTabListPlus version 3.0.1
[01:52:31 INFO]: Looking for an update...
[01:52:31 INFO]: You are already running the latest version.
[01:52:31 INFO]: Bridge plugin status:
[01:52:31 INFO]: Installed on: Skyblock, Lobby
[01:52:31 INFO]: Bridge status is not available for servers without players.
[01:52:31 INFO]: Thank you for using BungeeTabListPlus.
```

**Comment by Kryniowesegryderiusz** [comment]
I saw that there is old playerOrder naming. And when I changed it from `alphabetically` to `name` I have that one:
```
[02:09:44 ERROR] [BungeeTabListPlus.Krynio]: [Krynio] Unexpected error
java.lang.NullPointerException: null
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.onTeamPacketPreprocess(AbstractTabOverlayHandler.java:1020) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.onTeamPacket(AbstractTabOverlayHandler.java:284) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.LowMemoryTabOverlayHandlerImpl.onTeamPacket(LowMemoryTabOverlayHandlerImpl.java:42) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:47) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:47) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:56) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:35) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:303) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:417) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-294.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by CodeCrafter47** [comment]
Your first issue has already been fixed with the 3.0.2 update. I have made some changes in the latest dev-build that should also fix your second issue.

**Comment by JasonHorkles** [comment]
I'm still getting things like this and I'm on 3.0.3-SNAPSHOT
`[18:00:33 ERROR] [BungeeTabListPlus]: Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/default.yml
java.lang.IllegalArgumentException: firstIndex < getSize()
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at de.codecrafter47.taboverlay.config.area.Area.createChild(Area.java:35) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.updateLayout(ListComponentView.java:225) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.onAreaUpdated(ListComponentView.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.TableComponentView.updateLayout(TableComponentView.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.TableComponentView.onAreaUpdated(TableComponentView.java:53) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.updateLayout(ListComponentView.java:216) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.onAreaUpdated(ListComponentView.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.RectangularContentView.onAreaUpdated(RectangularContentView.java:54) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.RectangularContentView.updateTabListSize(RectangularContentView.java:75) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.RectangularContentView.onActivation(RectangularContentView.java:47) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24) ~[?:?]
        at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**Comment by JasonHorkles** [comment]
It might be because I have `connectedFirst` in the player order list but I didn't see any warnings telling me to change it like it did with the other stuff which is now fixed. I also couldn't find anything else to replace `connectedFirst` but idk if that's even the problem or not

**Comment by Kryniowesegryderiusz** [comment]
Now its working, but sometimes i got disconnected while changing server with
```
[21:13:46 INFO]: [Krynio|/89.64.56.153:10237] <-> ServerConnector [Lobby] has connected
[21:13:48 INFO]: [/185.230.160.243:52420] <-> InitialHandler is pinging
[21:13:48 INFO]: [Krynio|/89.64.56.153:10237] <-> ServerConnector [Skyblock] has connected
[21:13:49 INFO]: [/89.64.56.153:10237|Krynio] <-> DownstreamBridge <-> [Lobby] has disconnected
[21:13:49 ERROR]: [/89.64.56.153:10237|Krynio] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at codecrafter47.bungeetablistplus.handler.TabOverlayHandlerImpl.sendPacket(TabOverlayHandlerImpl.java:40) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.onDeactivated(AbstractTabOverlayHandler.java:1277) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$AbstractContentOperationModeHandler.invalidate(AbstractTabOverlayHandler.java:525) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:472) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-309.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
[21:13:49 INFO]: [Krynio] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
```

**Comment by CodeCrafter47** [comment]
Those issues should be fixed now. Using `connectedFirst` is fine.

**Comment by JasonHorkles** [comment]
Still getting this on build 850
```
[16:13:04 ERROR] [BungeeTabListPlus]: Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/admin.yml
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Number
        at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier.lambda$getToDoubleFunction$1(DataHolderPlaceholderDataProviderSupplier.java:43) ~[?:?]
        at java.util.Comparator.lambda$comparingDouble$8dcf42ea$1(Comparator.java:532) ~[?:1.8.0_222]
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217) ~[?:1.8.0_222]
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216) ~[?:1.8.0_222]
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:1.8.0_222]
        at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_222]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_222]
        at java.util.ArrayList.sort(ArrayList.java:1462) ~[?:1.8.0_222]
        at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.activate(OrderedPlayerSetImpl.java:105) ~[?:?]
        at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.addListener(OrderedPlayerSetImpl.java:179) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.PlayersComponentView.onActivation(PlayersComponentView.java:62) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ContainerComponentView.onActivation(ContainerComponentView.java:30) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.onActivation(ListComponentView.java:46) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.TableComponentView.onActivation(TableComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ListComponentView.onActivation(ListComponentView.java:46) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.RectangularContentView.onActivation(RectangularContentView.java:45) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24) ~[?:?]
        at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
Is there something I might've done wrong or are they just more bugs?

**Comment by CodeCrafter47** [comment]
It looks like you have been hit by yet another bug. I am sorry for this. Can you try the latest dev-build and check if it fixes the issue?

**Comment by JasonHorkles** [comment]
With these updates do I need to update the bridge as well or just the main plugin?

**Comment by JasonHorkles** [comment]
Also it seems to work without errors so far, thanks!

**Comment by CodeCrafter47** [comment]
It is not necessary to update the bridge plugin.

**Comment by Kryniowesegryderiusz** [comment]
After update i get warning that
WARNING: Unsuitable placeholder in playerOrder option: `luckperms_meta_tab`. This placeholder cannot be used for sorting.

The main feature of latest updates was custom playerOrder sorting by placeholders, especially to fix luckeperms sorting issues with rank weight. Why luckperms_meta placeholder cannot be used for sorting though? :C

**Comment by CodeCrafter47** [comment]
I think this is probably a false warning. Does it sort correctly if you use that placeholder?

**Comment by Kryniowesegryderiusz** [comment]
No, it ignores sorting by that placeholder

**Comment by Kryniowesegryderiusz** [comment]
```
[20:46:39 ERROR] [BungeeTabListPlus]: Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/skyblock_def.yml
java.lang.IllegalArgumentException: firstIndex < getSize()
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at de.codecrafter47.taboverlay.config.area.Area.createChild(Area.java:35) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.PlayersComponentView.onAreaUpdated(PlayersComponentView.java:118) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.DynamicSizeContentView.onAreaUpdated(DynamicSizeContentView.java:43) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.DynamicSizeContentView.updateTabListSize(DynamicSizeContentView.java:59) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.DynamicSizeContentView.onActivation(DynamicSizeContentView.java:36) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31) ~[?:?]
        at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24) ~[?:?]
        at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by CodeCrafter47** [comment]
I have made a new update (3.0.6) that should fix that issue as well as the false warnings related to the player order.

**Comment by Kryniowesegryderiusz** [comment]
```
[23:59:17] [Netty Worker IO Thread #14/ERROR] [BungeeTabListPlus.SpanishVR]: [SpanishVR] Unexpected error
java.lang.NullPointerException: null
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.onTeamPacket(AbstractTabOverlayHandler.java:1122) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.onTeamPacket(AbstractTabOverlayHandler.java:342) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.LowMemoryTabOverlayHandlerImpl.onTeamPacket(LowMemoryTabOverlayHandlerImpl.java:42) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:47) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:47) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:56) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:35) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-315.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

Here we are again XD
And since 3.0.0 i have problem, that after a few hours ping is massively dropping on servers. I do not have confirmation, that its caused by BTLP, but thats the only plugin I have been chanking recently :C

**Comment by CodeCrafter47** [comment]
That issue now too is fixed on the latest dev-build.

I can not say much with regard to potential memory leaks. I think it is possible that those exist, but I did not find any during my testing. That does not mean much since I can not test every possible way to use the plugin.

Bugs in the plugin that lead to error messages in the proxy log such as the ones you posted above are likely to also cause some memory leakage. If you are still seeing the issue with those fixed it is probably worth investigating (e.g. by creating a memory dump).

**Comment by Kryniowesegryderiusz** [comment]
```
[15:11:52] [BungeeTabListPlus Pool Thread #3/WARN] [BungeeTabListPlus]: An unexpected error occurred: null
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at java.lang.Object.wait(Object.java:328) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252) ~[waterfall-317.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317]
	at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:336) ~[waterfall-317.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317]
	at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.onDetach(ConfigTabOverlayProvider.java:88) ~[?:?]
	at de.codecrafter47.taboverlay.AbstractPlayerTabOverlayProvider.detach(AbstractPlayerTabOverlayProvider.java:38) ~[?:?]
	at de.codecrafter47.taboverlay.TabOverlayProviderSet.lambda$removeProviders$3(TabOverlayProviderSet.java:132) ~[?:?]
	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-317.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-317.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-317.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
Someting new :P

**Comment by CodeCrafter47** [comment]
Did this happen during shutdown of the proxy or during normal operation?

**Comment by Kryniowesegryderiusz** [comment]
I dont remember. Its possible that was on shutdown

**Comment by CodeCrafter47** [comment]
Closing this as all the bugs presented here have been fixed. If you stumble across any other bugs, please open a new issue.
