### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Predzzy** [CodeCrafter47/BungeeTabListPlus#493]
Updated to the Latest Version of HexagonMC Bungeecord and Latest Version of BungeeTabListPlus i get this error and when i try to connect to my server my minecraft crashes

21.01 13:28:28 [Server] WARNING [BungeeTabListPlus] An unexpected error occurred: java.lang.NullPointerException
21.01 13:28:28 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException
21.01 13:28:28 [Server] INFO at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:349)
21.01 13:28:28 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.attach(ExcludedServersTabOverlayProvider.java:45)
21.01 13:28:28 [Server] INFO at de.codecrafter47.taboverlay.TabOverlayProviderSet.lambda$addProvider$1(TabOverlayProviderSet.java:107)
21.01 13:28:28 [Server] INFO at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
21.01 13:28:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
21.01 13:28:28 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
21.01 13:28:28 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21.01 13:28:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.01 13:28:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.01 13:28:28 [Server] INFO at java.lang.Thread.run(Thread.java:748)
21.01 13:28:28 [Server] INFO Caused by: java.lang.NullPointerException
21.01 13:28:28 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.compute(MatchingStringsCollection.java:63)
21.01 13:28:28 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.contains(MatchingStringsCollection.java:54)
21.01 13:28:28 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.lambda$attach$0(ExcludedServersTabOverlayProvider.java:43)
21.01 13:28:28 [Server] INFO at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
21.01 13:28:28 [Server] INFO at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
21.01 13:28:28 [Server] INFO ... 7 more
21.01 13:28:30 [Server] WARNING [BungeeTabListPlus] An unexpected error occurred: java.lang.NullPointerException
21.01 13:28:30 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException
21.01 13:28:30 [Server] INFO at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:349)
21.01 13:28:30 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.attach(ExcludedServersTabOverlayProvider.java:45)
21.01 13:28:30 [Server] INFO at de.codecrafter47.taboverlay.TabOverlayProviderSet.lambda$addProvider$1(TabOverlayProviderSet.java:107)
21.01 13:28:30 [Server] INFO at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
21.01 13:28:30 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
21.01 13:28:30 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
21.01 13:28:30 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21.01 13:28:30 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.01 13:28:30 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.01 13:28:30 [Server] INFO at java.lang.Thread.run(Thread.java:748)
21.01 13:28:30 [Server] INFO Caused by: java.lang.NullPointerException
21.01 13:28:30 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.compute(MatchingStringsCollection.java:63)
21.01 13:28:30 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.contains(MatchingStringsCollection.java:54)
21.01 13:28:30 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.lambda$attach$0(ExcludedServersTabOverlayProvider.java:43)
21.01 13:28:30 [Server] INFO at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
21.01 13:28:30 [Server] INFO at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
21.01 13:28:30 [Server] INFO ... 7 more
21.01 13:28:33 [Server] WARNING [Frozqen] -> UpstreamBridge - NativeIoException: readAddress(..) failed: Connection reset by peer
21.01 13:28:33 [Server] INFO [Frozqen] disconnected with: NativeIoException : readAddress(..) failed: Connection reset by peer
21.01 13:28:33 [Server] INFO [Frozqen] -> UpstreamBridge has disconnected
21.01 13:28:35 [Server] WARNING [Predzzy] -> UpstreamBridge - NativeIoException: readAddress(..) failed: Connection reset by peer
21.01 13:28:35 [Server] INFO [Predzzy] disconnected with: NativeIoException : readAddress(..) failed: Connection reset by peer
21.01 13:28:35 [Server] INFO [Predzzy] -> UpstreamBridge has disconnected

**Comment by CodeCrafter47** [comment]
The error you posted above should now be fixed as of version 3.0.4. But I do not know if the plugin is generally able to run on HexagonMC. A possible option to run it with old Minecraft version is to use the latest version of BungeeCord and run either ViaVersion or ProtocolSupport to add support for older versions of the game.

**Comment by Predzzy** [comment]
Updated to the latest version of bungeecord but now can't join with 1.7 clients? can i put viaversion into the bungeecord files or what?

**Comment by Predzzy** [comment]
Nvm updated to the latest version of bungeecord and still get this error

21.01 15:13:26 [Server] WARNING [BungeeTabListPlus] An unexpected error occurred: java.lang.NullPointerException
21.01 15:13:26 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException
21.01 15:13:26 [Server] INFO at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:349)
21.01 15:13:26 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.attach(ExcludedServersTabOverlayProvider.java:45)
21.01 15:13:26 [Server] INFO at de.codecrafter47.taboverlay.TabOverlayProviderSet.lambda$addProvider$1(TabOverlayProviderSet.java:107)
21.01 15:13:26 [Server] INFO at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
21.01 15:13:26 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
21.01 15:13:26 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
21.01 15:13:26 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21.01 15:13:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.01 15:13:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.01 15:13:26 [Server] INFO at java.lang.Thread.run(Thread.java:748)
21.01 15:13:26 [Server] INFO Caused by: java.lang.NullPointerException
21.01 15:13:26 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.compute(MatchingStringsCollection.java:63)
21.01 15:13:26 [Server] INFO at codecrafter47.bungeetablistplus.util.MatchingStringsCollection.contains(MatchingStringsCollection.java:54)
21.01 15:13:26 [Server] INFO at codecrafter47.bungeetablistplus.tablist.ExcludedServersTabOverlayProvider.lambda$attach$0(ExcludedServersTabOverlayProvider.java:43)
21.01 15:13:26 [Server] INFO at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
21.01 15:13:26 [Server] INFO at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
21.01 15:13:26 [Server] INFO ... 7 more

**Comment by CodeCrafter47** [comment]
ViaVersion should be installed on your spigot servers. For 1.7 support you are probably better of with ProtocolSupport which I think needs to be installed on both BungeeCord and your Spigot server. However I strongly recommend you read the documentation of those plugins and make sure you understand what they do before installing them on your server.

The above error has been fixed in the latest version of the plugin -> you are not running the latest version. Use `/btlp status` to check which version you are running. The latest version currently is `3.0.4`.
