### ISSUE TITLE
(Question) Scoreboard teams

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [CodeCrafter47/BungeeTabListPlus#80]
Before I go all out with everything, I've read that to solve the general issue of scoreboard teams being a derp, you have to set the tab_size to 80. Where do you set that?
If that isn't the solution, or you have no idea what I'm talking about, I'll probably post a huge wall of text showing what's wrong with scoreboard teams when this plugin is introduced.
Thanks in advance!

**Comment by CodeCrafter47** [comment]
You can change that option in default.yml

**Comment by Aquafina-water-bottle** [comment]
Sorry for the late response. The person who takes cares of the server changed it, but the same issues are still here. I'll just list them out (and how to replicate them.) I'm not sure why this plugin affects this honestly, or if this plugin isn't exactly affecting it, but a combination of different plugins is doing this.

**Team option: color**
It doesn't show the colors of players on the tab list, when put on a display, or above their player name. It does show the color when they die though.
_/scoreboard teams add test
/scoreboard teams option test color green
/scoreboard players join test @p_

**Team option: nametagVisibility**
This option doesn't affect anything to change whether teams see or don't see name tags.
_/scoreboard teams add test
/scoreboard teams option test nametagVisibility never
/scoreboard players join test @p
/scoreboard players join test A-friend_ (Look at each other's heads and see if you can see each other's nametags. You shouldn't be able to.)

**Team option: seeFriendlyInvisibles**
This option also doesn't work. Normally, you can see invisible people as if you were in gamemode 3.
_/scoreboard teams add test
/scoreboard teams option test seeFriendlyInvisibles true
/scoreboard players join test @p_ (f5 after to see if you can see yourself)

**Objectives: setdisplay sidebar.team.x**
This should show a display for players with a team color of x only. This simply doesn't work.
_/scoreboard teams add test
/scoreboard objectives add test dummy
/scoreboard teams option test color green
/scoreboard players join test @p
/scoreboard players set @p test 0
/scoreboard objectives setdisplay sidebar.team.green_

To undo everything: _/scoreboard objectives remove test_ (and) _/scoreboard teams remove test_

Note: I think we're using the most current version of the plugin to date.

**Comment by CodeCrafter47** [comment]
Using BungeeTabListPlus can break scoreboard functionality in some cases which results in the effects you describe. However other plugins can also break scoreboard functionality. To be make sure BungeeTabListPlus is the reason your scoreboard teams don't work as expected check the BungeeCord console. If there are lots of warnings similar the following:
```
10:30:30 [WARNUNG] [BungeeTabListPlus] Scoreboard teams don't work with tab_size < 80.
Transforming packet Team(name=blue, mode=4, displayName=null, prefix=null, suffix=null, nameTagVisibility=null, collisionRule=null, color=0, friendlyFire=0, players=[CodeCrafter47])
10:30:30 [WARNUNG] [BungeeTabListPlus] Scoreboard teams don't work with tab_size < 80.
Transformed packet Team(name=blue, mode=4, displayName=null, prefix=null, suffix=null, nameTagVisibility=null, collisionRule=null, color=0, friendlyFire=0, players=[])
10:30:30 [WARNUNG] [BungeeTabListPlus] Scoreboard teams don't work with tab_size < 80.
Transforming packet Team(name=blue, mode=3, displayName=null, prefix=null, suffix=null, nameTagVisibility=null, collisionRule=null, color=0, friendlyFire=0, players=[CodeCrafter47])
10:30:31 [WARNUNG] [BungeeTabListPlus] Scoreboard teams don't work with tab_size < 80.
Transformed packet Team(name=blue, mode=3, displayName=null, prefix=null, suffix=null, nameTagVisibility=null, collisionRule=null, color=0, friendlyFire=0, players=[])
```
then BungeeTabListPlus is the reason your scoreboard teams don't work. Otherwise it is caused by another plugin.

**Comment by dutchy1001** [comment]
I have the same error you describe above ([pastebin](http://pastebin.com/qwu7Mnit)), but only when I join the server while using PremiumVanish and join vanished. If I join normally the error doesn't appear. 
If I swap ingame between vanish and unvanish there is no error.

As you know about this issue, is there a fix for it besides turning the scoreboard off??
Or, should this be addressed by the PremiumVanish team in my case??

**Comment by CodeCrafter47** [comment]
As the error message implies you can fix it by setting tab_size to 80.

I think the reason PremiumVanish uses the scoreboard is so vanished players see other vanished players with a blue nametag. If you don't need that functionality you can just ignore the error.

**Comment by dutchy1001** [comment]
tab-size is set to 80

**Comment by CodeCrafter47** [comment]
And the tab list has 80 slots if you press tab?

**Comment by dutchy1001** [comment]
Screenshot should clear this up, each row has 20 slots

![2016-03-08_13 16 51](https://cloud.githubusercontent.com/assets/5569980/13602693/114b4d04-e530-11e5-96f0-2f503979962a.png)

**Comment by CodeCrafter47** [comment]
In that case you will not experience any issues.

The warning when you join the server is printed because at that point the plugin doesn't know how big your tab list will be. The plugin will send the correct scoreboard teams to the client as soon as it figures out the tab size.

**Comment by dutchy1001** [comment]
How does the plugin not know what size the tab-list is? That is set in the config. I don't think it should depend on a player joining when the tab_size is set to max.

I will make a post at the PV page to see if they can make it compatible if there is nothing else that would fix it from your end

**Comment by CodeCrafter47** [comment]
Even if you don't do that, BungeeTabListPlus allows different configurations (with a different tab size) for different players depending on which server a player is on or which group a player has. The plugin will test which configuration applies for a player when the tab list is sent to the player.

Until the tab list is sent to a player the first time the plugin assumes that the size of the tab list will be the one configured in BungeeCords config.yml. I'll probably change that behavior to fix you specific error.

**Comment by dutchy1001** [comment]
So if I set the bungee config.yml tab-size it should be fixed?
I never thought about that to check for that option in the bungee config, I presumed you were talking about your own config.
Testing this after hitting enter and let you know

**Comment by Wqrld** [comment]
i have the tab size to 80 but i still cant see colored and /or hidden nametags on the newest version. no errors tho
